In [6]:

import pandas as pd

df = pd.read_csv(r'C:\Users\alire\sp500_project\sp500_companies.csv')
print(df.head())

  Exchange Symbol              Shortname               Longname  \
0      NMS   AAPL             Apple Inc.             Apple Inc.
1      NMS   NVDA     NVIDIA Corporation     NVIDIA Corporation
2      NMS   MSFT  Microsoft Corporation  Microsoft Corporation
3      NMS   AMZN       Amazon.com, Inc.       Amazon.com, Inc.
4      NMS  GOOGL          Alphabet Inc.          Alphabet Inc.

                   Sector                        Industry  Currentprice  \
0              Technology            Consumer Electronics        254.49
1              Technology                  Semiconductors        134.70
2              Technology       Software - Infrastructure        436.60
3       Consumer Cyclical                 Internet Retail        224.92
4  Communication Services  Internet Content & Information        191.41

       Marketcap        Ebitda  Revenuegrowth           City State  \
0  3846819807232  1.346610e+11          0.061      Cupertino    CA
1  3298803056640  6.118400e+10          1.224    Santa Clara    CA
2  3246068596736  1.365520e+11          0.160        Redmond    WA
3  2365033807872  1.115830e+11          0.110        Seattle    WA
4  2351625142272  1.234700e+11          0.151  Mountain View    CA

         Country  Fulltimeemployees  \
0  United States           164000.0
1  United States            29600.0
2  United States           228000.0
3  United States          1551000.0
4  United States           181269.0

                                 Longbusinesssummary    Weight
0  Apple Inc. designs, manufactures, and markets ...  0.069209
1  NVIDIA Corporation provides graphics and compu...  0.059350
2  Microsoft Corporation develops and supports so...  0.058401
3  Amazon.com, Inc. engages in the retail sale of...  0.042550
4  Alphabet Inc. offers various products and plat...  0.042309

In [7]:
import pandas as pd
import matplotlib.pyplot as plt

# Load your CSV file (replace path if needed)
df = pd.read_csv(r'C:\Users\alire\sp500_project\sp500_companies.csv')

# Show first 5 rows to understand the data
print(df.head())

  Exchange Symbol              Shortname               Longname  \
0      NMS   AAPL             Apple Inc.             Apple Inc.
1      NMS   NVDA     NVIDIA Corporation     NVIDIA Corporation
2      NMS   MSFT  Microsoft Corporation  Microsoft Corporation
3      NMS   AMZN       Amazon.com, Inc.       Amazon.com, Inc.
4      NMS  GOOGL          Alphabet Inc.          Alphabet Inc.

                   Sector                        Industry  Currentprice  \
0              Technology            Consumer Electronics        254.49
1              Technology                  Semiconductors        134.70
2              Technology       Software - Infrastructure        436.60
3       Consumer Cyclical                 Internet Retail        224.92
4  Communication Services  Internet Content & Information        191.41

       Marketcap        Ebitda  Revenuegrowth           City State  \
0  3846819807232  1.346610e+11          0.061      Cupertino    CA
1  3298803056640  6.118400e+10          1.224    Santa Clara    CA
2  3246068596736  1.365520e+11          0.160        Redmond    WA
3  2365033807872  1.115830e+11          0.110        Seattle    WA
4  2351625142272  1.234700e+11          0.151  Mountain View    CA

         Country  Fulltimeemployees  \
0  United States           164000.0
1  United States            29600.0
2  United States           228000.0
3  United States          1551000.0
4  United States           181269.0

                                 Longbusinesssummary    Weight
0  Apple Inc. designs, manufactures, and markets ...  0.069209
1  NVIDIA Corporation provides graphics and compu...  0.059350
2  Microsoft Corporation develops and supports so...  0.058401
3  Amazon.com, Inc. engages in the retail sale of...  0.042550
4  Alphabet Inc. offers various products and plat...  0.042309

In [8]:
# Check data types and non-null counts
print(df.info())

# Count missing values per column
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 502 entries, 0 to 501
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Exchange             502 non-null    object
 1   Symbol               502 non-null    object
 2   Shortname            502 non-null    object
 3   Longname             502 non-null    object
 4   Sector               502 non-null    object
 5   Industry             502 non-null    object
 6   Currentprice         502 non-null    float64
 7   Marketcap            502 non-null    int64
 8   Ebitda               473 non-null    float64
 9   Revenuegrowth        499 non-null    float64
 10  City                 502 non-null    object
 11  State                482 non-null    object
 12  Country              502 non-null    object
 13  Fulltimeemployees    493 non-null    float64
 14  Longbusinesssummary  502 non-null    object
 15  Weight               502 non-null    float64
dtypes: float64(5), int64(1), object(10)
memory usage: 62.9+ KB
None
Exchange                0
Symbol                  0
Shortname               0
Longname                0
Sector                  0
Industry                0
Currentprice            0
Marketcap               0
Ebitda                 29
Revenuegrowth           3
City                    0
State                  20
Country                 0
Fulltimeemployees       9
Longbusinesssummary     0
Weight                  0
dtype: int64

In [10]:
print(df.columns.tolist())

['Exchange', 'Symbol', 'Shortname', 'Longname', 'Sector', 'Industry', 'Currentprice', 'Marketcap', 'Ebitda', 'Revenuegrowth', 'City', 'State', 'Country', 'Fulltimeemployees', 'Longbusinesssummary', 'Weight']

In [11]:
# Drop rows where Revenuegrowth is missing
df_clean = df.dropna(subset=['Revenuegrowth'])

# Show the first few cleaned rows
df_clean.head()

,Exchange,Symbol,Shortname,Longname,Sector,Industry,Currentprice,Marketcap,Ebitda,Revenuegrowth,City,State,Country,Fulltimeemployees,Longbusinesssummary,Weight
0,NMS,AAPL,Apple Inc.,Apple Inc.,Technology,Consumer Electronics,254.49,3846819807232,1.346610e+11,0.061,Cupertino,CA,United States,164000.0,"Apple Inc. designs, manufactures, and markets ...",0.069209
1,NMS,NVDA,NVIDIA Corporation,NVIDIA Corporation,Technology,Semiconductors,134.70,3298803056640,6.118400e+10,1.224,Santa Clara,CA,United States,29600.0,NVIDIA Corporation provides graphics and compu...,0.059350
2,NMS,MSFT,Microsoft Corporation,Microsoft Corporation,Technology,Software - Infrastructure,436.60,3246068596736,1.365520e+11,0.160,Redmond,WA,United States,228000.0,Microsoft Corporation develops and supports so...,0.058401
3,NMS,AMZN,"Amazon.com, Inc.","Amazon.com, Inc.",Consumer Cyclical,Internet Retail,224.92,2365033807872,1.115830e+11,0.110,Seattle,WA,United States,1551000.0,"Amazon.com, Inc. engages in the retail sale of...",0.042550
4,NMS,GOOGL,Alphabet Inc.,Alphabet Inc.,Communication Services,Internet Content & Information,191.41,2351625142272,1.234700e+11,0.151,Mountain View,CA,United States,181269.0,Alphabet Inc. offers various products and plat...,0.042309

In [12]:
# Filter for companies with Revenuegrowth > 0.2 (20%)
growth_stocks = df_clean[df_clean['Revenuegrowth'] > 0.2]

# Show top growth companies
growth_stocks[['Symbol', 'Shortname', 'Revenuegrowth', 'Marketcap']].sort_values(by='Revenuegrowth', ascending=False).head(10)

    Symbol                        Shortname  Revenuegrowth      Marketcap
307     SW             Smurfit WestRock plc          1.632    27713910784
384   SMCI       Super Micro Computer, Inc.          1.430    18497998848
223    PRU       Prudential Financial, Inc.          1.334    41939349504
1     NVDA               NVIDIA Corporation          1.224  3298803056640
96      MU          Micron Technology, Inc.          0.933   100408999936
215    NEM              Newmont Corporation          0.847    43579867136
341   CINF  Cincinnati Financial Corporatio          0.833    22598461440
216    DFS      Discover Financial Services          0.605    43475628032
37      BX                  Blackstone Inc.          0.541   207208415232
196    VST                     Vistra Corp.          0.539    47614623744

In [14]:
import pandas as pd

df = pd.read_csv(r'C:\Users\alire\sp500_project\sp500_companies.csv')
print(df.head())

  Exchange Symbol              Shortname               Longname  \
0      NMS   AAPL             Apple Inc.             Apple Inc.
1      NMS   NVDA     NVIDIA Corporation     NVIDIA Corporation
2      NMS   MSFT  Microsoft Corporation  Microsoft Corporation
3      NMS   AMZN       Amazon.com, Inc.       Amazon.com, Inc.
4      NMS  GOOGL          Alphabet Inc.          Alphabet Inc.

                   Sector                        Industry  Currentprice  \
0              Technology            Consumer Electronics        254.49
1              Technology                  Semiconductors        134.70
2              Technology       Software - Infrastructure        436.60
3       Consumer Cyclical                 Internet Retail        224.92
4  Communication Services  Internet Content & Information        191.41

       Marketcap        Ebitda  Revenuegrowth           City State  \
0  3846819807232  1.346610e+11          0.061      Cupertino    CA
1  3298803056640  6.118400e+10          1.224    Santa Clara    CA
2  3246068596736  1.365520e+11          0.160        Redmond    WA
3  2365033807872  1.115830e+11          0.110        Seattle    WA
4  2351625142272  1.234700e+11          0.151  Mountain View    CA

         Country  Fulltimeemployees  \
0  United States           164000.0
1  United States            29600.0
2  United States           228000.0
3  United States          1551000.0
4  United States           181269.0

                                 Longbusinesssummary    Weight
0  Apple Inc. designs, manufactures, and markets ...  0.069209
1  NVIDIA Corporation provides graphics and compu...  0.059350
2  Microsoft Corporation develops and supports so...  0.058401
3  Amazon.com, Inc. engages in the retail sale of...  0.042550
4  Alphabet Inc. offers various products and plat...  0.042309

In [15]:
df_clean = df.dropna(subset=['Revenuegrowth', 'Marketcap', 'Currentprice', 'Ebitda'])

In [17]:
df_clean = df_clean.copy()  # Make a full copy first
df_clean['Ebitda_margin'] = df_clean['Ebitda'] / df_clean['Marketcap']

In [18]:
df_clean = df.dropna(subset=['Revenuegrowth', 'Marketcap', 'Currentprice', 'Ebitda']).copy()
df_clean['Ebitda_margin'] = df_clean['Ebitda'] / df_clean['Marketcap']

In [19]:
# Filter for growth criteria
growth_stocks = df_clean[
    (df_clean['Revenuegrowth'] > 0.10) &
    (df_clean['Ebitda_margin'] > 0) &
    (df_clean['Marketcap'] > 10e9) &
    (df_clean['Currentprice'] < 500)
]

# Show top candidates
growth_stocks[['Shortname', 'Sector', 'Industry', 'Revenuegrowth', 'Ebitda_margin', 'Marketcap', 'Currentprice']].sort_values(
    by='Revenuegrowth', ascending=False).head(10)

,Shortname,Sector,Industry,Revenuegrowth,Ebitda_margin,Marketcap,Currentprice
307,Smurfit WestRock plc,Consumer Cyclical,Packaging & Containers,1.632,0.078408,27713910784,53.28
384,"Super Micro Computer, Inc.",Technology,Computer Hardware,1.430,0.070526,18497998848,31.59
223,"Prudential Financial, Inc.",Financial Services,Insurance - Life,1.334,0.132509,41939349504,117.83
1,NVIDIA Corporation,Technology,Semiconductors,1.224,0.018547,3298803056640,134.70
96,"Micron Technology, Inc.",Technology,Semiconductors,0.933,0.089076,100408999936,90.12
215,Newmont Corporation,Basic Materials,Gold,0.847,0.137885,43579867136,38.28
341,Cincinnati Financial Corporatio,Financial Services,Insurance - Property & Casualty,0.833,0.179747,22598461440,144.57
196,Vistra Corp.,Utilities,Utilities - Independent Power Producers,0.539,0.126432,47614623744,139.95
60,RTX Corporation,Industrials,Aerospace & Defense,0.492,0.081084,155037220864,116.48
385,Seagate Technology Holdings PLC,Technology,Computer Hardware,0.491,0.065570,18468683776,87.31

In [20]:
# Export growth stocks to CSV for Tableau
growth_stocks.to_csv('growth_stocks_filtered.csv', index=False)
print("Exported successfully to growth_stocks_filtered.csv")

Exported successfully to growth_stocks_filtered.csv

In [21]:
print(df_clean[['Revenuegrowth', 'Ebitda_margin']].describe())
print(df_clean[['Revenuegrowth', 'Ebitda_margin']].isnull().sum())
print(df_clean[(df_clean['Revenuegrowth'] == 0) | (df_clean['Ebitda_margin'] == 0)])

       Revenuegrowth  Ebitda_margin
count     470.000000     470.000000
mean        0.070023       0.097177
std         0.179207       0.074071
min        -0.484000      -0.155826
25%         0.002000       0.051977
50%         0.049000       0.079274
75%         0.106750       0.127539
max         1.632000       0.648407
Revenuegrowth    0
Ebitda_margin    0
dtype: int64
Empty DataFrame
Columns: [Exchange, Symbol, Shortname, Longname, Sector, Industry, Currentprice, Marketcap, Ebitda, Revenuegrowth, City, State, Country, Fulltimeemployees, Longbusinesssummary, Weight, Ebitda_margin]
Index: []

In [23]:
print(df.columns.tolist())

['Exchange', 'Symbol', 'Shortname', 'Longname', 'Sector', 'Industry', 'Currentprice', 'Marketcap', 'Ebitda', 'Revenuegrowth', 'City', 'State', 'Country', 'Fulltimeemployees', 'Longbusinesssummary', 'Weight']

In [24]:
import pandas as pd

# Step 1: Load the CSV
df = pd.read_csv(r'C:\Users\alire\sp500_project\sp500_companies.csv')

# Step 2: Convert columns to numeric where needed
cols_to_convert = ['Marketcap', 'Ebitda', 'Revenuegrowth']
for col in cols_to_convert:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Step 3: Drop rows missing important data
df_clean = df.dropna(subset=['Sector', 'Marketcap', 'Ebitda', 'Revenuegrowth'])

print(df_clean.head())

  Exchange Symbol              Shortname               Longname  \
0      NMS   AAPL             Apple Inc.             Apple Inc.
1      NMS   NVDA     NVIDIA Corporation     NVIDIA Corporation
2      NMS   MSFT  Microsoft Corporation  Microsoft Corporation
3      NMS   AMZN       Amazon.com, Inc.       Amazon.com, Inc.
4      NMS  GOOGL          Alphabet Inc.          Alphabet Inc.

                   Sector                        Industry  Currentprice  \
0              Technology            Consumer Electronics        254.49
1              Technology                  Semiconductors        134.70
2              Technology       Software - Infrastructure        436.60
3       Consumer Cyclical                 Internet Retail        224.92
4  Communication Services  Internet Content & Information        191.41

       Marketcap        Ebitda  Revenuegrowth           City State  \
0  3846819807232  1.346610e+11          0.061      Cupertino    CA
1  3298803056640  6.118400e+10          1.224    Santa Clara    CA
2  3246068596736  1.365520e+11          0.160        Redmond    WA
3  2365033807872  1.115830e+11          0.110        Seattle    WA
4  2351625142272  1.234700e+11          0.151  Mountain View    CA

         Country  Fulltimeemployees  \
0  United States           164000.0
1  United States            29600.0
2  United States           228000.0
3  United States          1551000.0
4  United States           181269.0

                                 Longbusinesssummary    Weight
0  Apple Inc. designs, manufactures, and markets ...  0.069209
1  NVIDIA Corporation provides graphics and compu...  0.059350
2  Microsoft Corporation develops and supports so...  0.058401
3  Amazon.com, Inc. engages in the retail sale of...  0.042550
4  Alphabet Inc. offers various products and plat...  0.042309

In [27]:
# Step 3: Sector-Level Grouping & Aggregation

sector_summary = df_clean.groupby('Sector').agg({
    'Marketcap': 'sum',             # Total market cap per sector
    'Ebitda': 'mean',               # Average EBITDA
    'Revenuegrowth': 'mean',        # Average revenue growth
    'Symbol': 'count'               # Number of companies
}).rename(columns={
    'Marketcap': 'Total_Marketcap',
    'Ebitda': 'Avg_Ebitda',
    'Revenuegrowth': 'Avg_RevenueGrowth',
    'Symbol': 'Company_Count'
}).reset_index()

# Sort by total market cap
sector_summary = sector_summary.sort_values(by='Total_Marketcap', ascending=False)

# Display the summary
print(sector_summary)

                    Sector  Total_Marketcap    Avg_Ebitda  Avg_RevenueGrowth  \
9               Technology   17266187948032  7.719694e+09           0.115827
1   Communication Services    7635955917824  2.441419e+10           0.052476
2        Consumer Cyclical    6372352768000  6.235455e+09           0.067436
6               Healthcare    5190430794752  6.161793e+09           0.077097
5       Financial Services    3955246706176  8.869586e+09           0.156553
7              Industrials    3764601742336  3.902160e+09           0.045143
3       Consumer Defensive    3253838582784  6.398985e+09           0.010297
4                   Energy    1598671836672  1.170329e+10           0.007727
10               Utilities    1257369774080  5.087530e+09           0.044156
8              Real Estate     995633945600  2.150882e+09           0.081267
0          Basic Materials     864553002496  3.643587e+09           0.019409

    Company_Count
9              81
1              21
2              55
6              62
5              38
7              70
3              37
4              22
10             32
8              30
0              22

In [28]:
# Total market cap (to calculate percentage share)
total_marketcap = sector_summary['Total_Marketcap'].sum()

# Add % Market Share and Sector Ranking
sector_summary['Marketcap_Share_%'] = (sector_summary['Total_Marketcap'] / total_marketcap) * 100
sector_summary['Sector_Rank'] = sector_summary['Total_Marketcap'].rank(ascending=False).astype(int)

# Optional: Format as percent (only for display)
sector_summary['Avg_RevenueGrowth_%'] = sector_summary['Avg_RevenueGrowth'] * 100

In [29]:
# Save final version for Tableau
sector_summary.to_csv(r'C:\Users\alire\sp500_project\sector_summary_for_tableau.csv', index=False)

In [30]:

# Save final version for Tableau
sector_summary.to_csv(r'C:\Users\alire\sp500_project\sector_summary_for_tableau.csv', index=False)

In [2]:
!pip install yfinance

Collecting yfinance
  Downloading yfinance-0.2.61-py2.py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: pandas>=1.3.0 in c:\users\alire\anaconda3\lib\site-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in c:\users\alire\anaconda3\lib\site-packages (from yfinance) (1.26.4)
Requirement already satisfied: requests>=2.31 in c:\users\alire\anaconda3\lib\site-packages (from yfinance) (2.32.3)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.11-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\alire\anaconda3\lib\site-packages (from yfinance) (3.10.0)
Requirement already satisfied: pytz>=2022.5 in c:\users\alire\anaconda3\lib\site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\alire\anaconda3\lib\site-packages (from yfinance) (2.4.2)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-3.18.1.tar.gz (3.0 MB)
     ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
     ----------------- ---------------------- 1.3/3.0 MB 7.4 MB/s eta 0:00:01
     ---------------------------------------- 3.0/3.0 MB 8.8 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\alire\anaconda3\lib\site-packages (from yfinance) (4.12.3)
Collecting curl_cffi>=0.7 (from yfinance)
  Downloading curl_cffi-0.11.1-cp39-abi3-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\alire\anaconda3\lib\site-packages (from yfinance) (4.25.3)
Collecting websockets>=13.0 (from yfinance)
  Downloading websockets-15.0.1-cp312-cp312-win_amd64.whl.metadata (7.0 kB)
Requirement already satisfied: soupsieve>1.2 in c:\users\alire\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: cffi>=1.12.0 in c:\users\alire\anaconda3\lib\site-packages (from curl_cffi>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\alire\anaconda3\lib\site-packages (from curl_cffi>=0.7->yfinance) (2025.4.26)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\alire\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\alire\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\alire\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\alire\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\alire\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.2.3)
Requirement already satisfied: pycparser in c:\users\alire\anaconda3\lib\site-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.21)
Requirement already satisfied: six>=1.5 in c:\users\alire\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.16.0)
Downloading yfinance-0.2.61-py2.py3-none-any.whl (117 kB)
Downloading curl_cffi-0.11.1-cp39-abi3-win_amd64.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 1.4/1.4 MB 14.8 MB/s eta 0:00:00
Downloading multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Downloading websockets-15.0.1-cp312-cp312-win_amd64.whl (176 kB)
Building wheels for collected packages: peewee
  Building wheel for peewee (pyproject.toml): started
  Building wheel for peewee (pyproject.toml): finished with status 'done'
  Created wheel for peewee: filename=peewee-3.18.1-py3-none-any.whl size=139098 sha256=96d5697b8ffad409a86f7a3a4dc15871b1fcb7edbee029885b000865a0a0c778
  Stored in directory: c:\users\alire\appdata\local\pip\cache\wheels\1a\57\6a\bb71346381d0d911cd4ce3026f1fa720da76707e4f01cf27dd
Successfully built peewee
Installing collected packages: peewee, multitasking, websockets, curl_cffi, yfinance
Successfully installed curl_cffi-0.11.1 multitasking-0.0.11 peewee-3.18.1 websockets-15.0.1 yfinance-0.2.61

In [3]:
import yfinance as yf
print("yfinance is working!")

yfinance is working!

In [4]:
import yfinance as yf
import pandas as pd

# Sample list of tickers
tickers = ['AAPL', 'MSFT', 'GOOGL', 'AMZN']

data = []
for ticker in tickers:
    stock = yf.Ticker(ticker)
    info = stock.info
    data.append({
        'Symbol': ticker,
        'Sector': info.get('sector'),
        'Marketcap': info.get('marketCap'),
        'Revenuegrowth': info.get('revenueGrowth'),
        'PE': info.get('trailingPE'),
        'PEG': info.get('pegRatio')
    })

df = pd.DataFrame(data)
df.to_csv("valuation_performance.csv", index=False)

In [5]:
df = df.drop(columns=['PEG'])

In [9]:
import pandas as pd
import yfinance as yf

# Step 1: Get all S&P 500 tickers from Wikipedia
url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
table = pd.read_html(url)
sp500_table = table[0]
tickers = sp500_table['Symbol'].tolist()

# Step 2: Fetch data for each ticker
data = []
for ticker in tickers:
    try:
        stock = yf.Ticker(ticker)
        info = stock.info
        data.append({
            'Symbol': ticker,
            'Sector': info.get('sector'),
            'Marketcap': info.get('marketCap'),
            'Revenuegrowth': info.get('revenueGrowth'),
            'PE': info.get('trailingPE'),
            'PEG': info.get('pegRatio'),
            'Longname': info.get('longName')
        })
    except Exception as e:
        print(f"Skipping {ticker} due to error: {e}")

# Step 3: Convert to DataFrame and save
df = pd.DataFrame(data)
df.to_csv("full_sp500_valuation_performance.csv", index=False)

print("Data saved to full_sp500_valuation_performance.csv")

Data saved to full_sp500_valuation_performance.csv

In [8]:
import os
print(os.getcwd())

C:\Users\alire